language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - SYMFONY_VERSION=2.1.*
    - SYMFONY_VERSION=2.2.*
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=dev-master

matrix:
    allow_failures:
        - env: SYMFONY_VERSION=dev-master

before_script:
    - curl -sS http://getcomposer.org/installer | php
    - php composer.phar require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - php composer.phar update

script: phpunit --coverage-text --coverage-clover ./build/logs/clover.xml

after_script: php vendor/bin/coveralls
